stages:
  - build
 

image: node:15.12.0-stretch
variables:
 Deploy: "prosite zakinu kuda nado"  #"http://77.220.209.125:8095"
build:
   stage: build
   script:
#    - apt-get update -y > /dev/null && apt-get install openssh-client sshpass wget -y > /dev/null
#    - npm cache clear --force
#    - npm config set strict-ssl false
#    - npm config set registry "http://registry.npmjs.org/"
    - npm install
    - node ./fix-crypto.js
    - npm run build:prod
    - sh .ci-notify.sh â˜‘ï¸ğŸ‘â˜‘ï¸
   artifacts:
    expire_in: 1 week
    paths:
      - dist
   only:
    - develop
